OPENAI_API_KEY = "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"


[snowflake]
ACCOUNT = "qu54329.ca-central-1.aw"
USER = "ROSHNI"
PASSWORD = "Roshbala@19"
DATABASE = "STREAM_HACKATHON"
SCHEMA = "STREAMLIT"
WAREHOUSE = "COMPUTE_WH"

[streamlit]
SUPABASE_URL = "<https://htifawancstvxvmxsquo.supabase.co>"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0aWZhd2FuY3N0dnh2bXhzcXVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTEwNDU3MTEsImV4cCI6MjAwNjYyMTcxMX0.VMD1OL7UF0fKpXJCr5771O2stQxUiaBSTTBFInBqhE4"


